blog_application/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("", include("public_site.urls")),  # Public site
    path('admin/', admin.site.urls),
    path('web_admin/', include('web_admin.urls')),  # Custom web_admin route
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) \
  + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

web_admin/news_letter/urls.py
# web_admin/category/urls.py
from django.urls import path
from . import views
from django.conf.urls.static import static
from django.conf import settings

app_name = 'news_letter'

urlpatterns = [
    path('', views.news_letters_list, name='news_letters_list'),
    path('create/', views.news_letter_create, name='news_letter_create'),
    path('<int:pk>/edit/', views.news_letter_edit, name='news_letter_edit'),
    path('<int:pk>/delete/', views.news_letter_delete, name='news_letter_delete'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

web_admin/urls.py
from django.urls import path, include
from . import views

urlpatterns = [
    path('', views.dashboard, name='web_admin_dashboard'),
    path("auth/", include("web_admin.authentication.urls", namespace="authentication")),
    path('category/', include('web_admin.category.urls', namespace='category')),
    path('post/', include('web_admin.post.urls', namespace='post')),
    path('group/', include('web_admin.group.urls', namespace='group')),
    path('tag/', include('web_admin.tag.urls', namespace='tag')),
    path('user/', include('web_admin.user.urls', namespace='user')),
    path('comment/', include('web_admin.comment.urls', namespace='comment')),
    path('myaccount/', include('web_admin.myaccount.urls', namespace='myaccount')),
]

web_admin/news_letter/models.py
from django.db import models
from django.contrib.auth.models import User, Group
from ckeditor.fields import RichTextField

# Create your models here.
class NewsLetter(models.Model):
    title = models.TextField(max_length=255)
    subject = models.TextField(max_length=255)
    content = RichTextField()
    status = models.IntegerField(default=0)
    author = models.ForeignKey(User, on_delete=models.CASCADE, related_name='news_letters', null=True)
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='created_news_letters')
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    
    class Meta:
        db_table = 'news_letters'
        
    def __str__(self):
        return self.title
    
    

web_admin/news_letter/forms.py
from django import forms
from .models import NewsLetter
from django.contrib.auth.models import Group
from ckeditor.widgets import CKEditorWidget

class NewsLetterForm(forms.ModelForm):
    
    class Meta:
        model = NewsLetter
        fields = ['title', 'subject', 'content']
        widgets = {
            'title': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Enter News Letter title'}),
            'subject': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Enter News Letter subject'}),
            'content': forms.CharField(widget=CKEditorWidget(attrs={'class': 'form-control', 'rows': 20})),
        }
        
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs) 
    def clean_title(self):
        title = self.cleaned_data.get('title')

        if len(title) < 5:
            raise forms.ValidationError("Given title is too short.")
        
        return title

web_admin/news_letter/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.urls import reverse
from .models import NewsLetter
from .forms import NewsLetterForm
from django.contrib import messages

# Create your views here.
def news_letters_list(request):
    news_letters = NewsLetter.objects.all()
    context = {
        "news_letters": news_letters,
        "breadcrumb_title": "News Letters",
        'title': 'News Letters',
        "breadcrumb": [
            {"text": "News Letters", "url": reverse('news_letter:news_letters_list')},
        ]
    }

    return render(request, 'news_letters/list.html', context)

def news_letter_create(request):
    form = NewsLetterForm(request.POST or None) 
            
    if request.method == "POST":
        if form.is_valid():
            news_letter = form.save(commit=False)
            news_letter.user = request.user
            news_letter.save()
            messages.success(request, "News Letter created successfully.")
            return redirect('news_letter:news_letters_list')

    context = {
        "form": form,
        "title": "News Letters",
        "text": "Create News Letter",
        "breadcrumb": [
            {"text": "Create News Letter", "url": reverse('news_letter:news_letters_list')},
        ]
    }
    return render(request, 'news_letters/form.html', context)


def news_letter_edit(request, pk):
    news_letter = get_object_or_404(NewsLetter, pk=pk)
    form = NewsLetterForm(request.POST or None, request.FILES or None, instance=news_letter)
            
    if request.method == "POST" and form.is_valid():
        if form.is_valid():
            print('Yes1') 
            news_letter = form.save(commit=False)
            news_letter.user = request.user
            news_letter.save()
            messages.success(request, "News Letter updated successfully.")
            return redirect('news_letter:news_letters_list')

    context = {
        "form": form,
        "title": "News Letters",
        "text": "Edit News Letter",
        "breadcrumb": [
            {"text": "Edit News Letter", "url": reverse('news_letter:news_letters_list')},
        ]
    }
    return render(request, 'news_letters/form.html', context)


def news_letter_delete(request, pk):
    news_letter = get_object_or_404(NewsLetter, pk=pk)
    news_letter.delete()
    messages.success(request, "News Letter deleted successfully.")
    return redirect('news_letter:news_letters_list')

web_admin/news_letter/templates/news_letters/form.html
{% extends "layout/base.html" %}
{% load static %}

{% block title %}{{title}}{% endblock %}

{% block content %}
<div class="row">
    <div class="col-sm-12">
        <div class="card">
            <div class="card-header">
                <div class="d-flex align-items-center justify-content-between">
                    <h4 class="mb-0">{{text}}</h4>
                </div>
            </div>
            <div class="card-body">
                <form method="post" enctype="multipart/form-data">
                    {% csrf_token %}
                    <div class="mb-3">
                        <label class="form-label" for="{{ form.title.id_for_label }}">Title</label>
                        {{ form.title }}
                        {% if form.title.errors %}
                            <div class="text-danger">{{ form.title.errors }}</div>
                        {% endif %}
                    </div>

                    <div class="mb-3">
                        <label class="form-label" for="{{ form.subject.id_for_label }}">Subject</label>
                        {{ form.subject }}
                        {% if form.subject.errors %}
                            <div class="text-danger">{{ form.subject.errors }}</div>
                        {% endif %}
                    </div>                

                    <div class="mb-3">
                        <label class="form-label" for="{{ form.content.id_for_label }}">Content</label>
                        <div class="row">
                            {{ form.media }}
                            {{ form.content }}
                            {% if form.content.errors %}
                                <div class="text-danger">{{ form.content.errors }}</div>
                            {% endif %}
                        </div>
                    </div>

                    {% comment %} <div class="mb-3">
                        <label for="{{ form.image.id_for_label }}" class="form-label">News Letter Image</label>
                        <input type="file" name="image" id="image" class="form-control">
                        {% if form.image.errors %}
                            <div class="text-danger">{{ form.image.errors }}</div>
                        {% endif %}
                        {% if news_letter and news_letter.image %}
                            <img src="{{ news_letter.image.url }}" alt="News Letter Image" class="img-fluid mt-2" width="150">
                        {% endif %}
                    </div> {% endcomment %}

                    {% comment %} <div class="mb-3">
                        <label class="form-label" for="{{ form.group.id_for_label }}">Group</label>
                        {{ form.group }}
                        {% if form.group.errors %}
                            <div class="text-danger">{{ form.group.errors }}</div>
                        {% endif %}
                    </div> {% endcomment %}

                    {% comment %} <div class="mb-3">
                        <label class="form-label" for="{{ form.status.id_for_label }}">Status</label>
                        {{ form.status }}
                        {% if form.status.errors %}
                            <div class="text-danger">{{ form.status.errors }}</div>
                        {% endif %}
                    </div> {% endcomment %}
                    <button type="submit" class="btn btn-primary">{% if news_letter %} Update {% else %} Create {% endif %}</button>
                    <a href="{% url 'news_letter:news_letters_list' %}" class="btn btn-secondary">Cancel</a>
                </form>
            </div>
        </div>
    </div>
</div>
{% endblock %}

{% block page_css %}
<link href="https://cdn.jsdelivr.net/npm/select2@4.0.13/dist/css/select2.min.css" rel="stylesheet" />
{% endblock %}

{% block page_js %}
<script src="https://cdn.jsdelivr.net/npm/select2@4.0.13/dist/js/select2.min.js"></script>

<script>
    $(document).ready(function() {
        $('.form-control[multiple]').select2({
            placeholder: "Select tags",
            allowClear: true
        });
    });
</script>
{% endblock %}

web_admin/news_letter/templates/news_letters/list.html
{% extends "layout/base.html" %}
{% load static %}

{% block title %}{{title}}{% endblock %}

{% block page_css %}
<!-- [Page specific CSS] start -->
<link rel="stylesheet" href="{% static 'css/plugins/dataTables.bootstrap5.min.css' %}">
<!-- [Page specific CSS] end -->
{% endblock %}

{% block content %}
<div class="row">
    <div class="col-sm-12">
        {% comment %} <div class="card">
            <div class="card-header">
                <h4 class="mb-0">Advanced Search</h4>
            </div>
            <div class="card-body">
                <form class="row row-cols-md-auto g-3 align-items-center" method="GET" action="">
                    <div class="col-12">
                        <select name="category" class="form-control">
                            <option value="">All Categories</option>
                            {% for category in categories %}
                                <option value="{{ category.id }}" {% if request.GET.category == category.id|stringformat:"s" %}selected{% endif %}>
                                    {{ category.name }}
                                </option>
                            {% endfor %}
                        </select>
                    </div>
                    <div class="col-12">
                        <button type="submit" class="btn btn-primary">Submit</button>
                        <a href="{% url 'blog:blog_list' %}" class="btn btn-secondary">Clear</a>
                    </div>
                </form>
            </div>
        </div> {% endcomment %}

        <div class="card">
            <div class="card-header">
                <div class="d-flex align-items-center justify-content-between">
                    <h4 class="mb-0">News Letter Management</h4>
                    <a href="{% url 'news_letter:news_letter_create' %}" class="btn btn-primary">Add News Letter</a>
                </div>
            </div>
            <div class="card-body">
                <div class="dt-responsive">
                    <table id="dom-jqry" class="table table-striped table-bordered nowrap">
                        <thead>
                            <tr>
                                <th>Title</th>
                                <th>Author</th>
                                <th>Status</th>
                                <th>Created At</th>
                                <th>Action</th>
                            </tr>
                        </thead>
                        <tbody>
                            {% for news_letter in news_letters %}
                            <tr>
                                <td>{{ news_letter.title }}</td>
                                
                                <td>{{ news_letter.user.username }}</td>
                                <td>
                                    {% if news_letter.status %}
                                    <span class="badge bg-success">Published</span>
                                    {% else %}
                                    <span class="badge bg-secondary">Draft</span>
                                    {% endif %}
                                </td>
                                <td>{{ news_letter.created_at }}</td>
                                <td> <a href="{% url 'news_letter:news_letter_edit' news_letter.pk %}" class="btn btn-sm btn-warning">Edit</a>
                                    <a href="{% url 'news_letter:news_letter_delete' news_letter.pk %}" class="btn btn-sm btn-danger" onclick="return confirm('Are you sure?');">Delete</a></td>
                            </tr>
                            {% endfor %}
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

{% block page_js %}
<!-- [Page Specific JS] start -->
<!-- datatable Js -->
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
<script src="{% static 'js/plugins/dataTables.min.js' %}"></script>
<script src="{% static 'js/plugins/dataTables.bootstrap5.min.js' %}"></script>
<script>// [ DOM/jquery ]
    var total, pageTotal;
    var table = $('#dom-jqry').DataTable();
</script>
<!-- [Page Specific JS] end -->
{% endblock %}