blog_application/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("", include("public_site.urls")),  # Public site
    path('admin/', admin.site.urls),
    path('web_admin/', include('web_admin.urls')),  # Custom web_admin route
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) \
  + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

web_admin/category/urls.py
# web_admin/category/urls.py
from django.urls import path
from .views import CategoryView

app_name = 'category'

urlpatterns = [
    path('', CategoryView().list, name='category_list'),
    path('create/', CategoryView().form, name='category_create'),
    path('<int:id>/edit/', CategoryView().form, name='category_edit'),
    path('<int:id>/delete/', CategoryView().delete, name='category_delete'),
    path("datatable", CategoryView().datatable, name="category_datatable"),
]

web_admin/urls.py
from django.urls import path, include
from . import views

urlpatterns = [
    path('', views.dashboard, name='web_admin_dashboard'),
    path("auth/", include("web_admin.authentication.urls", namespace="authentication")),
    path('category/', include('web_admin.category.urls', namespace='category')),
    path('post/', include('web_admin.post.urls', namespace='post')),
    path('group/', include('web_admin.group.urls', namespace='group')),
    path('tag/', include('web_admin.tag.urls', namespace='tag')),
    path('user/', include('web_admin.user.urls', namespace='user')),
    path('comment/', include('web_admin.comment.urls', namespace='comment')),
    path('myaccount/', include('web_admin.myaccount.urls', namespace='myaccount')),
]

web_admin/category/models.py
from django.db import models
from django.utils.text import slugify

class Category(models.Model):
    name = models.CharField(max_length=255, unique=True)
    slug = models.SlugField(unique=True, max_length=255, null = True, blank = True)
    description = models.TextField(blank=True, null=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    image = models.ImageField(upload_to='category_images/', blank=True, null=True)

    def save(self, *args, **kwargs):
        self.slug = slugify(self.name)
        super().save(*args, **kwargs)
    class Meta:
        db_table = 'categories'

    def __str__(self):
        return self.name

web_admin/category/forms.py
from django import forms
from .models import Category

class CategoryForm(forms.ModelForm):
    name = forms.CharField(required=False,widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Enter category name'}))
    description = forms.CharField(required=False, widget=forms.Textarea(attrs={'class': 'form-control', 'placeholder': 'Enter description', 'rows': 4}))
    image = forms.ImageField(required=False)

    class Meta:
        model = Category
        fields = ['name', 'image', 'description']

    def clean_name(self):
        name = self.cleaned_data.get('name', '').strip()
        
        if not name:
            raise forms.ValidationError("Category name is required.")
                    
        qs = Category.objects.filter(name=name)
        if self.instance.pk:
            qs = qs.exclude(pk=self.instance.pk)
        if qs.exists():
            raise forms.ValidationError("Category with this name already exists.")

        return name
    
    def clean_description(self):
        description = self.cleaned_data.get('description', '').strip()
        
        if not description:
            raise forms.ValidationError("Category description is required.")
        return description
    
    def clean_image(self):
        image = self.cleaned_data.get("image")
        if not image:
            return None  # Ensure None is returned if no image is uploaded
        return image

web_admin/category/views.py
from web_admin.common.crud_views import CrudView
from django.db.models import Count
from .models import Category
from .forms import CategoryForm

class CategoryView(CrudView):
    module = 'Category'
    model = Category
    form_class = CategoryForm
    list_template_name = 'list.html' 
    form_template_name = 'form.html'
    redirect_url = 'category:category_list'

    def _shareData(self, page, data = {}):
        if page == 'List':
            return {
                'columns': ["Name","Total Posts", "Image", "Created At", "Actions"],
            }
    
    def _dt(self):
        return {
            'sort': ['name', 'total_posts', 'image', 'created_at'],
            'search': ['name__icontains'],
            'select': ['id', 'name', 'total_posts', 'image', 'created_at'], 
            'query': self.model.objects.annotate( total_posts=Count('posts') ).values('id', 'name', 'total_posts', 'image', 'created_at')     
        }

web_admin/category/templates/form.html
{% extends "layout/base.html" %}
{% load static %}

{% block title %}{{title}}{% endblock %}

{% block content %}
<div class="row">
    <div class="col-sm-12">
        <div class="card">
            <div class="card-body">
                <form method="post" enctype="multipart/form-data">
                    {% csrf_token %}
                    <div class="mb-3">
                        <label class="form-label" for="{{ form.name.id_for_label }}">Category Name</label>
                        {{ form.name }}
                        {% if form.name.errors %}
                            <div class="text-danger">{{ form.name.errors }}</div>
                        {% endif %}
                    </div>
                    <div class="mb-3">
                        <label for="{{ form.image.id_for_label }}" class="form-label">Category Image</label>
                        <input type="file" name="image" id="image" class="form-control">
                        {% if form.image.errors %}
                            <div class="text-danger">{{ form.image.errors }}</div>
                        {% endif %}
                        {% if category and category.image %}
                            <img src="{{ category.image.url }}" alt="Category Image" class="img-fluid mt-2" width="150">
                        {% endif %}
                    </div> 
                    <div class="mb-3">
                        <label class="form-label" for="{{ form.description.id_for_label }}">Description</label>
                        {{ form.description }}
                        {% if form.description.errors %}
                            <div class="text-danger">{{ form.description.errors }}</div>
                        {% endif %}
                    </div>
                    <button type="submit" class="btn btn-primary">Submit</button>
                    <a href="{% url 'category:category_list' %}" class="btn btn-secondary">Cancel</a>
                </form>
            </div>
        </div>
    </div>
</div>
{% endblock %}

web_admin/category/templates/list.html
{% extends "layout/base.html" %}
{% load static %}
{% load tags %}

{% block title %}{{title}}{% endblock %}

{% block page_css %}
    {% datatable 'css' %}
{% endblock %}

{% block content %}
<div class="row">
    <div class="col-sm-12">
        <div class="card">
            <div class="card-header">
                <div class="d-flex align-items-center justify-content-between">
                    <h4 class="mb-0">Category Management</h4>
                    {% if can_add_category %}
                        <a href="{% url 'category:category_create' %}" class="btn btn-primary">Add Category</a>
                    {% endif %}
                </div>
            </div>
            <div class="card-body">
                {% datatable 'table' table_id='categories' columns=columns %}
            </div>
        </div>
    </div>
</div>
{% endblock %}

{% block js %}
    {% datatable 'js' %}
    {% sweetalert 'js' %}
{% endblock %}

{% block script %}
    {% include 'layout/partials/_scripts.html' %}
    {% datatable 'script' %}
    {% sweetalert 'script' %}
    <script>
        $(function(){
            ajaxdatatable({
                selector: '#categories', 
                url: '{% url "category:category_datatable" %}',
                data: {
                    csrfmiddlewaretoken: "{{ csrf_token }}"
                },
                columns: [
                    { "data": "name" },
                    { "data": "total_posts", "searchable": false, "orderable": false }, 
                    {
                        "data": "image", 
                        "orderable": false,
                        "searchable": false,
                        "render": function(data, type, row) {
                            if (data) {
                                let imageUrl = `/media/${data}`;
                                return `<img src="${imageUrl}" alt="Image" style="width: 50px; height: 50px; object-fit: cover;">`;
                            } else {
                                return "<span>No Image</span>";
                            }
                        }
                    },
                    {
                        "data": "created_at",
                        "render": data => data ? new Date(data).toLocaleDateString('en-US') : "N/A"
                    },
                    { "data": "action", "searchable": false, "orderable": false, "render": function(data, type, row) {
                        let action = {};
                        {% if can_edit_category %}
                            action['edit'] = '{% url "category:category_edit" id=0 %}'.replace('0', row.id)
                        {% endif %}
                        {% if can_delete_category %}
                            action['delete'] = '{% url "category:category_delete" id=0 %}'.replace('0', row.id)
                        {% endif %}
                        return actionColumn(action)
                    }},
                ],
                order: [0, 'desc']
            })
        })  
        $(document).on('click', '#delete', function(e){
            e.preventDefault;

            var url = $(this).data('href');
            var fields = '{% csrf_token %}';

            sweetalert().then((result) => {
                if (result.isConfirmed) {
                    postform(url, fields)
                }
            })
        })
            
    </script>
{% endblock %}